//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CalGro
    {
        public int Id { get; set; }
        public string Date { get; set; }
        [Required]
        [Range(0,15000, ErrorMessage="Price range should be Zero to Fifteen Thousand")]
        public int Price { get; set; }
        [Required]
        public string Product { get; set; }
    }
}
