//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealIinfo
    {
        public int Id { get; set; }
        public int Member_ID { get; set; }
        public int Lunch { get; set; }
        public int Dinner { get; set; }
        public int breakfast { get; set; }
    }
}
